[tool.black]
line-length = 88
target_version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git          # root of the project
    | \.mypy_cache
    | \.venv
    | \.env
    | __pycache__
    | cdk.out
  )/
)
'''
skip-string-normalization = 'true'
# diff = 'true'
